## Biblioteca Numpy (lembre-se de instalar o numpy no prompt de comando primeiro)

In [30]:
import numpy as np

### 1- Básico

In [31]:
# Criando matriz 3x3
a = np.array([(1,2,3),(4,5,6),(7,8,9)])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
# Descobrindo a Forma da matriz
a.shape

(3, 3)

In [33]:
# Descobrindo o número de elementos
a.size

9

In [34]:
# Matriz com valor Zero 4x3
c = np.zeros([4,3])

# Matriz com valor Um 4x3
d = np.ones([4,3])

# Matriz quadrada 10x10 com diagonal Principal
e = np.eye(10)

# Matriz Identidade 10x10 (Mesma da matriz acima, apenas mostrando duas formas de fazer)
f = np.identity(10)

print(c)
print("")
print(d)
print("")
print(e)
print("")
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [35]:
# Matriz randomica com valores decimais 4x3
rand = np.random.rand(4,3)

# Matriz randomica com valores inteiros 4x3 (de-4 até 8)
inte = np.random.randint(-4,8, size=(4,3))

print(rand)
print("")
print(inte)

[[0.93370179 0.68393667 0.21679875]
 [0.34230771 0.15370926 0.96902075]
 [0.90274035 0.12227465 0.38899259]
 [0.61048838 0.51482476 0.8826202 ]]

[[ 3  0  4]
 [ 7  2  2]
 [ 3  0 -4]
 [ 6  4 -4]]


### 2- Acrescentando/Mudando elementos especificos, linhas, colunas, etc

In [36]:
h = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(h)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
# Pegar um elemento especifico [L, C] (Lembrnado que a linha 1, para o python, é a linha 0)
h1 = h[1, 5]

# Pegar uma linha especifica 
h2 = h[0, :]

# Pegar uma coluna especifica
h3 = h[:, 2]

print(h1)
print("")
print(h2)
print("")
print(h3)

13

[1 2 3 4 5 6 7]

[ 3 10]


In [42]:
# Substituindo
h[1,5] = 20

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
# Fazendo a mesma coisa, mas agora para um array de duas matrizes
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
ElementoEspecifico = b[0,1,1]

print(b)
print("")
print(ElementoEspecifico)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

4


In [44]:
Substituição = b[:,1,:] = [[9,9,9],[8,8]]

print(Substituição)

[[9, 9, 9], [8, 8]]


In [45]:
# Acrescentando uma matriz dentro da outra
MatrizInicial = np.ones((5,5))
print(MatrizInicial)

MatrizInput = np.zeros((3,3))
MatrizInput[1,1] = 9

MatrizInicial[1:-1,1:-1] = MatrizInput

print("")
print(MatrizInput)
print("")
print(MatrizInicial)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 3- Cálculos Matemáticos

In [48]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
soma = a + 2
subtração = a - 2
multiplicação = a * 2
divisão = a / 2
elevado = a ** 2
seno = np.sin(a)
cosseno = np.cos(a)

print(soma)
print("")
print(subtração)
print("")
print(multiplicação)
print("")
print(divisão)
print("")
print(elevado)
print("")
print(seno)
print("")
print(cosseno)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [46]:
# Demais Cálculos do Numpy

maior = a.max()
menor = a.min()
soma = a.sum()
média = a.mean()
DesvPad = a.std()

print("O maior valor da matriz é {}".format(str(maior)))
print("O menor valor da matriz é {}".format(str(menor)))
print("A soma dos valores da matriz é {}".format(str(soma)))
print("A média dos valores da matriz é {}".format(str(média)))
print("O Desvio Padrão é {}".format(str(DesvPad)))

O maior valor da matriz é 9
O menor valor da matriz é 1
A soma dos valores da matriz é 45
A média dos valores da matriz é 5.0
O Desvio Padrão é 2.581988897471611


### 4- Álgebra Linear

In [53]:
# Multiplicação de Matrizes
I = np.ones((2,3))
print(I)
print("")

J = np.full((3,2), 3)
print(J)

np.matmul(I,J)

[[1. 1. 1.]
 [1. 1. 1.]]

[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [54]:
# Descobrindo a Identidade de uma Matriz
K = np.identity(3)
np.linalg.det(K)

1.0

In [ ]:
## Outrs calculos no doc (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinante
# Traço
# Decomposição Singular Vertical
# Autovalores
# Matriz normal
# Inversa
# Etc...

### 5- Reorganizando Arrays

In [58]:
antes = np.array([[1,2,3,4],[5,6,7,8]])
print(antes)
print("")

depois = antes.reshape((4,2))
print(depois)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [59]:
# Vetores empilhados verticalmente
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
# Empilhados horizontalmente
np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])